name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create build directory
      run: mkdir -p dist
      
    - name: Bundle application
      run: |
        # Copy main files to dist
        cp package.json dist/
        cp README.md dist/
        cp index.js dist/
        
        # Copy source directories
        cp -r src/ dist/
        cp -r config/ dist/ 2>/dev/null || echo "No config directory"
        cp -r docs/ dist/ 2>/dev/null || echo "No docs directory"
        
        # Create production package.json
        node -e "
          const pkg = require('./package.json');
          delete pkg.devDependencies;
          delete pkg.scripts.test;
          pkg.scripts = {
            start: pkg.scripts.start,
            enhanced: pkg.scripts.enhanced,
            advanced: pkg.scripts.advanced,
            basic: pkg.scripts.basic,
            discord: pkg.scripts.discord
          };
          require('fs').writeFileSync('dist/package.json', JSON.stringify(pkg, null, 2));
        "
        
    - name: Install production dependencies
      run: |
        cd dist
        npm install --only=production
        
    - name: Create deployment archive
      run: |
        tar -czf iron-anarchy-bot-${{ matrix.node-version }}.tar.gz -C dist .
        
    - name: Generate documentation
      if: matrix.node-version == '18.x'
      run: |
        npx jsdoc -c jsdoc.conf.json -d dist/docs/ src/ || echo "JSDoc generation failed"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.node-version }}
        path: |
          iron-anarchy-bot-${{ matrix.node-version }}.tar.gz
          dist/
        retention-days: 14

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'DOCKER_EOF'
        FROM node:18-alpine
        
        # Set working directory
        WORKDIR /app
        
        # Install system dependencies
        RUN apk add --no-cache git
        
        # Copy package files
        COPY package*.json ./
        
        # Install dependencies
        RUN npm ci --only=production && npm cache clean --force
        
        # Copy application code
        COPY . .
        
        # Create non-root user
        RUN addgroup -g 1001 -S nodejs && \
            adduser -S minecraft -u 1001 -G nodejs
        
        # Change ownership and switch to non-root user
        RUN chown -R minecraft:nodejs /app
        USER minecraft
        
        # Expose port (if needed for web interface)
        EXPOSE 3000
        
        # Health check
        HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
          CMD node -e "console.log('Bot is healthy')" || exit 1
        
        # Default command
        CMD ["npm", "start"]
        DOCKER_EOF
        
    - name: Build Docker image
      run: |
        docker build -t iron-anarchy-minecraft-bot:latest .
        docker build -t iron-anarchy-minecraft-bot:${{ github.sha }} .
        
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-bot iron-anarchy-minecraft-bot:latest
        sleep 5
        docker logs test-bot
        docker stop test-bot || true
        
    - name: Save Docker image
      run: |
        docker save iron-anarchy-minecraft-bot:latest | gzip > iron-anarchy-bot-docker.tar.gz
        
    - name: Upload Docker artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: iron-anarchy-bot-docker.tar.gz
        retention-days: 7

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate documentation
      run: |
        mkdir -p docs/api
        npx jsdoc -c jsdoc.conf.json -d docs/api/ src/
        
        # Create a simple index.html for GitHub Pages
        cat > docs/index.html << 'HTML_EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Iron Anarchy Minecraft Bot Documentation</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .header { background: #2d3436; color: white; padding: 20px; border-radius: 5px; }
                .content { margin: 20px 0; }
                .link-button { display: inline-block; padding: 10px 20px; background: #0984e3; color: white; text-decoration: none; border-radius: 5px; margin: 5px; }
                .link-button:hover { background: #74b9ff; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Iron Anarchy Minecraft Bot</h1>
                <p>Enterprise-grade Minecraft automation bot documentation</p>
            </div>
            <div class="content">
                <h2>Documentation</h2>
                <a href="api/" class="link-button">API Documentation</a>
                <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot" class="link-button">GitHub Repository</a>
                <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot/releases" class="link-button">Releases</a>
            </div>
        </body>
        </html>
        HTML_EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        cname: minecraft-bot.ironanarchy.lol
      continue-on-error: true

  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run performance tests
      run: |
        # Create a simple performance test
        node -e "
          console.time('Bot startup time');
          try {
            require('./index.js');
            console.timeEnd('Bot startup time');
          } catch (error) {
            console.log('Bot startup test completed (expected to fail without config)');
            console.timeEnd('Bot startup time');
          }
        "
        
    - name: Memory usage test
      run: |
        node -e "
          const used = process.memoryUsage();
          console.log('Memory usage:');
          for (let key in used) {
            console.log(\`\${key}: \${Math.round(used[key] / 1024 / 1024 * 100) / 100} MB\`);
          }
        "
