name: Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build documentation
        run: npm run docs
        # Assuming you have a script in package.json for documentation generation
        # e.g. "docs": "documentation build src/** -f html -o docs"
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        if: github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
        with:
          path: './docs' # Path where documentation is generated
          
      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
        uses: actions/deploy-pages@v2
