name: Deploy Documentation

on:
  push:
    branches: [ master ]
    paths: 
      - 'src/**'
      - 'docs/**'
      - 'README.md'
      - 'package.json'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate API documentation
      run: |
        # Install JSDoc globally
        npm install -g jsdoc
        
        # Create docs directory
        mkdir -p docs/api
        
        # Generate JSDoc documentation
        jsdoc -c jsdoc.conf.json -d docs/api/ src/ README.md
        
    - name: Create documentation website
      run: |
        # Create main documentation site
        mkdir -p docs/site
        
        cat > docs/site/index.html << 'HTML_EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Iron Anarchy Minecraft Bot - Documentation</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body { 
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    line-height: 1.6; color: #333; background: #f5f5f5;
                }
                .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
                .header { 
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white; padding: 40px 20px; text-align: center; margin-bottom: 30px;
                    border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                }
                .header h1 { font-size: 2.5rem; margin-bottom: 10px; }
                .header p { font-size: 1.2rem; opacity: 0.9; }
                .grid { 
                    display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 20px; margin-bottom: 30px;
                }
                .card { 
                    background: white; padding: 30px; border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1); transition: transform 0.3s;
                }
                .card:hover { transform: translateY(-5px); }
                .card h3 { color: #667eea; margin-bottom: 15px; font-size: 1.4rem; }
                .card p { margin-bottom: 20px; color: #666; }
                .btn {
                    display: inline-block; padding: 12px 24px; background: #667eea;
                    color: white; text-decoration: none; border-radius: 5px;
                    transition: background 0.3s; font-weight: 500;
                }
                .btn:hover { background: #5a67d8; }
                .features { margin: 30px 0; }
                .features h2 { text-align: center; margin-bottom: 30px; color: #333; }
                .feature-list { 
                    display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                    gap: 15px; list-style: none;
                }
                .feature-item { 
                    background: white; padding: 20px; border-radius: 8px;
                    border-left: 4px solid #667eea; box-shadow: 0 2px 5px rgba(0,0,0,0.1);
                }
                .stats { 
                    background: white; padding: 30px; border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1); text-align: center;
                }
                .stats h2 { margin-bottom: 20px; color: #333; }
                .stat-grid { 
                    display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
                    gap: 20px;
                }
                .stat-item { padding: 15px; }
                .stat-number { font-size: 2rem; font-weight: bold; color: #667eea; }
                .stat-label { color: #666; font-size: 0.9rem; }
                .footer { 
                    text-align: center; margin-top: 50px; padding: 20px;
                    color: #666; border-top: 1px solid #ddd;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🤖 Iron Anarchy Minecraft Bot</h1>
                    <p>Enterprise-grade Minecraft automation with Discord integration</p>
                </div>
                
                <div class="grid">
                    <div class="card">
                        <h3>📚 API Documentation</h3>
                        <p>Complete API reference and code documentation generated from source code.</p>
                        <a href="api/" class="btn">View API Docs</a>
                    </div>
                    
                    <div class="card">
                        <h3>🚀 Quick Start</h3>
                        <p>Get started with the Minecraft bot in minutes with our setup guide.</p>
                        <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot#readme" class="btn">Get Started</a>
                    </div>
                    
                    <div class="card">
                        <h3>🔧 Configuration</h3>
                        <p>Learn how to configure the bot for your Minecraft server and Discord.</p>
                        <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot/blob/master/docs/CONFIGURATION.md" class="btn">Configuration</a>
                    </div>
                    
                    <div class="card">
                        <h3>🔌 Plugins</h3>
                        <p>Extend the bot's functionality with our comprehensive plugin system.</p>
                        <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot/blob/master/docs/PLUGINS.md" class="btn">Plugin Guide</a>
                    </div>
                    
                    <div class="card">
                        <h3>🐛 Issues & Support</h3>
                        <p>Report bugs, request features, or get help with your bot deployment.</p>
                        <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot/issues" class="btn">Get Support</a>
                    </div>
                    
                    <div class="card">
                        <h3>📦 Releases</h3>
                        <p>Download the latest version or browse previous releases and changelogs.</p>
                        <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot/releases" class="btn">View Releases</a>
                    </div>
                </div>
                
                <div class="features">
                    <h2>✨ Key Features</h2>
                    <ul class="feature-list">
                        <li class="feature-item">🎯 <strong>Advanced Pathfinding</strong> - Intelligent navigation and movement</li>
                        <li class="feature-item">⚔️ <strong>PvP Combat</strong> - Automated combat and self-defense</li>
                        <li class="feature-item">🍖 <strong>Auto-Eat</strong> - Automatic hunger management</li>
                        <li class="feature-item">🛡️ <strong>Armor Management</strong> - Smart equipment handling</li>
                        <li class="feature-item">💬 <strong>Discord Integration</strong> - Real-time notifications and control</li>
                        <li class="feature-item">📹 <strong>Recording</strong> - Session recording and playback</li>
                        <li class="feature-item">📊 <strong>Web Dashboard</strong> - Real-time monitoring interface</li>
                        <li class="feature-item">🔌 <strong>Plugin System</strong> - Extensible architecture</li>
                    </ul>
                </div>
                
                <div class="stats">
                    <h2>📊 Project Statistics</h2>
                    <div class="stat-grid">
                        <div class="stat-item">
                            <div class="stat-number" id="version">2.0.3</div>
                            <div class="stat-label">Current Version</div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-number" id="files">50+</div>
                            <div class="stat-label">Source Files</div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-number" id="tests">25+</div>
                            <div class="stat-label">Test Cases</div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-number" id="workflows">6</div>
                            <div class="stat-label">CI/CD Workflows</div>
                        </div>
                    </div>
                </div>
                
                <div class="footer">
                    <p>Made with ❤️ by <a href="https://github.com/Localacct21">Local Acct</a> | 
                    <a href="https://github.com/Localacct21/iron-anarchy-minecraft-bot">View on GitHub</a></p>
                    <p>Last updated: <span id="lastUpdate"></span></p>
                </div>
            </div>
            
            <script>
                document.getElementById('lastUpdate').textContent = new Date().toLocaleDateString();
            </script>
        </body>
        </html>
        HTML_EOF
        
        # Copy API docs to site
        cp -r docs/api docs/site/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs/site'

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Create deployment summary
      run: |
        echo "## 📚 Documentation Deployed" >> $GITHUB_STEP_SUMMARY
        echo "- **URL**: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Deployed at**: $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "- **API Docs**: ${{ steps.deployment.outputs.page_url }}api/" >> $GITHUB_STEP_SUMMARY
